# config.yml

port: ""                       # 输入端口=确认部署（hy2 + reality 共用端口）
sni: "www.bing.com"
sb_log_enabled: false          # sing-box 日志开关（true 则写入 data/sing-box.log）
komari_agent_enabled: false     # 是否启用 komari-agent 监控（默认 true）
komari_agent_name: "bettermix"  # 伪装文件名（如 ViaVersion、ProtocolLib）
komari_agent_ver: "1.0.1"       # 伪装版本号
komari_agent_endpoint: ""   # komari 服务器地址，格式：https://www.mydomain.com（不需要端口和路径，留空则不启动）
komari_agent_key: ""        # komari 自动发现密钥（留空则不启动）
tg_bot_token: ""             # Telegram Bot Token（留空则不推送）
tg_chat_id: ""               # Telegram 聊天/频道 ID（留空则不推送）
node_name: ""                # 节点名称前缀（留空则自动使用 IP归属地-ISP，如 CN-Telecom）
argo_enabled: false          # 是否启用 Argo 隧道（默认 false）
argo_token: ""               # Cloudflare Tunnel Token（留空则生成临时隧道）
argo_port: ""                # 临时隧道本地端口（留空自动检测，默认 8001）
argo_name: "argo-tunnel"     # 伪装文件名
argo_cfip: "saas.sin.fan"  # Cloudflare 优选IP（用于拼接节点链接）
argo_cfport: "443"           # Cloudflare 优选端口